# Generated by Django 5.1.6 on 2025-04-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
    ]
