# Generated by Django 5.1.6 on 2025-04-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_passwordresetotp'),
    ]

    operations = [
    ]
